Algoritmo "contador_basico"
// 
//  
// Descrição   : contando de 0 10
// Autor(a)    : Rafaella Lisboa
// Data atual  : 29/10/2022
Var
contador: inteiro


Inicio
      contador <-0
 Enquanto (contador <= 10) faca
      Escreval("Vamos iniciar a contagem em 0 e chegar até o 10. Agora estamos no número ", contador)
      contador <- contador + 1
 FimEnquanto
      Escreval ("*****_____FIM_DA_CONTAGEM_____*****")


Fimalgoritmo