Algoritmo "Par_ou_Impar"
// 
//      Jogo basico de par ou impar
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 05/10/2022
Var
   n : Inteiro


Inicio
      Escreval ("Fale um numero que irei dizer se é ÍMPAR ou PAR")
      Leia (n)
      Se (n % 2 = 0) Entao
         Escreval ("O numero ", N, " é PAR.")
      SeNao
           Escreval ("O número ", N, " é ÍMPAR")
      FimSe

Fimalgoritmo